version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: always
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
